[project]
name = "parcae"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.1",
    "pandas>=3.0.0",
]

[project.optional-dependencies]
train = [
    "matplotlib>=3.10.8",
]
